package com.resolvix.test.entity;

public class AutoGeneratedValueEntityField<S, T>
    extends AbstractEntityField<S, T>
    implements EntityField<S, T>
{
    private AutoGeneratedValueEntityField(
        String fieldName, Class<T> classT) {
        super(fieldName, classT, null);
    }

    public static <S, T> AutoGeneratedValueEntityField<S, T> of(
        String fieldName, Class<T> classT) {
        return new AutoGeneratedValueEntityField<>(
            fieldName, classT);
    }
}
